# Generated by Django 3.2.4 on 2021-06-12 20:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tinyurl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myurl',
            name='last_us_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 12, 20, 49, 51, 715643, tzinfo=utc), verbose_name='date of last using of url'),
        ),
        migrations.AlterField(
            model_name='myurl',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 12, 20, 49, 51, 715643, tzinfo=utc), verbose_name='date published'),
        ),
    ]
