# Generated by Django 3.2.4 on 2021-06-12 20:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tinyurl', '0002_auto_20210612_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myurl',
            name='last_us_date',
            field=models.DateTimeField(default=models.DateTimeField(default=datetime.datetime(2021, 6, 12, 20, 53, 37, 144359, tzinfo=utc), verbose_name='date published'), verbose_name='date of last using of url'),
        ),
        migrations.AlterField(
            model_name='myurl',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 12, 20, 53, 37, 144359, tzinfo=utc), verbose_name='date published'),
        ),
    ]
