# Generated by Django 3.2.4 on 2021-06-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinyurl', '0003_auto_20210612_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myurl',
            name='last_us_date',
            field=models.DateTimeField(default=models.DateTimeField(verbose_name='date published'), verbose_name='date of last using of url'),
        ),
        migrations.AlterField(
            model_name='myurl',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='myurl',
            name='tiny_url',
            field=models.CharField(max_length=200),
        ),
    ]
