# Generated by Django 3.2.4 on 2021-06-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinyurl', '0005_alter_myurl_last_us_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myurl',
            old_name='tiny_url',
            new_name='hash',
        ),
        migrations.AlterField(
            model_name='myurl',
            name='num_of_uses',
            field=models.IntegerField(default=0, verbose_name='the number of times the tiny url was used'),
        ),
    ]
